### ISSUE TITLE
请问 请求url 为什么提示No matching records found

### ISSUE THREAD

**Issue by 762219891** [lslvxy/bootstrapTable-treeView#11]
url:'data.json',
                 contentType: 'application/x-www-form-urlencoded; charset=utf-8',
               //data: data,

谷歌浏览器中出现该问题，火狐没有

**Comment by lslvxy** [comment]
查看bootstraptable文档吧，一般是response配置错了

**Comment by 762219891** [comment]
已经解决了  谢谢
