### ISSUE TITLE
你好，treeView:false，这个属性设置了false好像也不能分页呢？

### ISSUE THREAD

**Issue by myHoro** [lslvxy/bootstrapTable-treeView#7]
treeView:false设置了也不能分页，是不是有其他什么我没有设置好的？

**Comment by lslvxy** [comment]
不需要tree组件可以把插件去掉，pagination要改为true

**Comment by myHoro** [comment]
哦，其实是需要的 左边用的你写的tree组件展示，然后右边显示的就是普通的table表格了。就发现右边的不能分页了= =。

**Comment by lslvxy** [comment]
源码中强制设置pagination=false，再168行可以改下

**Comment by myHoro** [comment]
哇，弄好了。谢谢大佬！！！♪(＾∀＾●)ﾉ
