### ISSUE TITLE
你好，又打扰了。用rowAttributes这个属性自定义属性会报错escapeHTML is not defined

### ISSUE THREAD

**Issue by myHoro** [lslvxy/bootstrapTable-treeView#8]
如题，使用rowAttributes会报错escapeHTML is not defined。实在是自己不能解决，只能来请教你了。

**Comment by lslvxy** [comment]
能给出代码么

**Comment by myHoro** [comment]
rowAttributes:function(row){
	return{'myid':row.id}
},——这个是设置自定义属性的代码。
报错：Uncaught ReferenceError: escapeHTML is not defined；
           at o.BootstrapTable.initRow (VM9783 bootstraptable-treeview.js:202)
           at o.BootstrapTable.initBody (VM9783 bootstraptable-treeview.js:404)
报错行： htmlAttributes.push(sprintf('%s="%s"', key, escapeHTML(attributes[key])));   ——202行
                var tr = this.initRow(item, i, data, trFragments);  ——404行

**Comment by lslvxy** [comment]
tree插件的问题，代码已经修改。

**Comment by myHoro** [comment]
哇~好了，好了。谢谢大佬了~。<
